<?php

namespace App\Filament\Resources;

use App\Filament\Resources\PqrsResource\Pages;
use App\Filament\Resources\PqrsResource\RelationManagers;
use App\Models\Pqrs;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class PqrsResource extends Resource
{
    protected static ?string $model = Pqrs::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('Client Information')
                    ->schema([
                        Forms\Components\TextInput::make('first_name')
                            ->required()
                            ->maxLength(255),
                        Forms\Components\TextInput::make('last_name')
                            ->required()
                            ->maxLength(255),
                        Forms\Components\TextInput::make('email')
                            ->email()
                            ->required()
                            ->maxLength(255),
                        Forms\Components\TextInput::make('phone')
                            ->tel()
                            ->required()
                            ->maxLength(255),
                        Forms\Components\TextInput::make('document_number')
                            ->required()
                            ->maxLength(255),
                    ])->columns(2),

                Forms\Components\Section::make('PQRS Details')
                    ->schema([
                        Forms\Components\TextInput::make('cun')
                            ->disabled()
                            ->dehydrated(false) // Don't send to backend on create (generated by model)
                            ->visibleOn('edit'),
                        Forms\Components\Select::make('type')
                            ->options([
                                'peticion' => 'Petición',
                                'queja' => 'Queja',
                                'apelacion' => 'Recurso de Apelación',
                                'reposicion' => 'Recurso de Reposición',
                            ])
                            ->required(),
                        Forms\Components\TextInput::make('motive')
                            ->required()
                            ->maxLength(255),
                        Forms\Components\Textarea::make('description')
                            ->required()
                            ->columnSpanFull(),
                        Forms\Components\FileUpload::make('attachments')
                            ->multiple()
                            ->downloadable()
                            ->columnSpanFull(),
                        Forms\Components\Select::make('status')
                            ->options([
                                'pending' => 'Pending',
                                'in_progress' => 'In Progress',
                                'resolved' => 'Resolved',
                                'closed' => 'Closed',
                            ])
                            ->default('pending')
                            ->required(),
                    ])->columns(2),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('cun')
                    ->searchable()
                    ->sortable(),
                Tables\Columns\TextColumn::make('type')
                    ->badge()
                    ->color(fn (string $state): string => match ($state) {
                        'peticion' => 'info',
                        'queja' => 'warning',
                        'apelacion' => 'danger',
                        'reposicion' => 'danger',
                    }),
                Tables\Columns\TextColumn::make('first_name')
                    ->label('Client')
                    ->formatStateUsing(fn ($record) => $record->first_name . ' ' . $record->last_name)
                    ->searchable(['first_name', 'last_name']),
                Tables\Columns\TextColumn::make('status')
                    ->label('Estado')
                    ->badge()
                    ->color(fn (string $state): string => match ($state) {
                        'pending' => 'warning',
                        'in_progress' => 'info',
                        'resolved' => 'success',
                        'closed' => 'gray',
                    })
                    ->formatStateUsing(fn (string $state): string => match ($state) {
                        'pending' => 'Pendiente',
                        'in_progress' => 'En Progreso',
                        'resolved' => 'Resuelto',
                        'closed' => 'Cerrado',
                    }),
                Tables\Columns\TextColumn::make('deadline_at')
                    ->label('Fecha Límite')
                    ->date('d/m/Y')
                    ->sortable()
                    ->badge()
                    ->color(fn ($record) => 
                        $record->status === 'resolved' || $record->status === 'closed' ? 'gray' : (
                            $record->deadline_at < now() ? 'danger' : (
                                $record->deadline_at < now()->addDays(3) ? 'warning' : 'success'
                            )
                        )
                    ),
                Tables\Columns\TextColumn::make('created_at')
                    ->label('Radicado')
                    ->dateTime('d/m/Y H:i')
                    ->sortable(),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('status')
                    ->label('Estado')
                    ->options([
                        'pending' => 'Pendiente',
                        'in_progress' => 'En Progreso',
                        'resolved' => 'Resuelto',
                        'closed' => 'Cerrado',
                    ]),
                Tables\Filters\Filter::make('overdue')
                    ->label('Vencidos')
                    ->query(fn (Builder $query): Builder => $query->where('deadline_at', '<', now())->whereNotIn('status', ['resolved', 'closed'])),
                Tables\Filters\SelectFilter::make('type')
                    ->options([
                        'peticion' => 'Petición',
                        'queja' => 'Queja',
                        'apelacion' => 'Recurso de Apelación',
                        'reposicion' => 'Recurso de Reposición',
                    ]),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\Action::make('answer')
                    ->label('Responder')
                    ->icon('heroicon-o-chat-bubble-left-right')
                    ->color('success')
                    ->form([
                        Forms\Components\Textarea::make('answer')
                            ->label('Respuesta Oficial')
                            ->required()
                            ->rows(5),
                    ])
                    ->action(function (Pqrs $record, array $data): void {
                        $record->update([
                            'answer' => $data['answer'],
                            'answered_at' => now(),
                            'status' => 'resolved',
                        ]);
                    })
                    ->visible(fn (Pqrs $record) => !in_array($record->status, ['resolved', 'closed'])),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListPqrs::route('/'),
            'create' => Pages\CreatePqrs::route('/create'),
            'edit' => Pages\EditPqrs::route('/{record}/edit'),
        ];
    }
}
