<?php

namespace App\Filament\Resources;

use App\Filament\Resources\PqrsResource\Pages;
use App\Filament\Resources\PqrsResource\RelationManagers;
use App\Models\Pqrs;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class PqrsResource extends Resource
{
    protected static ?string $model = Pqrs::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('Client Information')
                    ->schema([
                        Forms\Components\TextInput::make('first_name')
                            ->required()
                            ->maxLength(255),
                        Forms\Components\TextInput::make('last_name')
                            ->required()
                            ->maxLength(255),
                        Forms\Components\TextInput::make('email')
                            ->email()
                            ->required()
                            ->maxLength(255),
                        Forms\Components\TextInput::make('phone')
                            ->tel()
                            ->required()
                            ->maxLength(255),
                        Forms\Components\TextInput::make('document_number')
                            ->required()
                            ->maxLength(255),
                    ])->columns(2),

                Forms\Components\Section::make('PQRS Details')
                    ->schema([
                        Forms\Components\TextInput::make('cun')
                            ->disabled()
                            ->dehydrated(false) // Don't send to backend on create (generated by model)
                            ->visibleOn('edit'),
                        Forms\Components\Select::make('type')
                            ->options([
                                'peticion' => 'Petición',
                                'queja' => 'Queja',
                                'apelacion' => 'Recurso de Apelación',
                                'reposicion' => 'Recurso de Reposición',
                            ])
                            ->required(),
                        Forms\Components\TextInput::make('motive')
                            ->required()
                            ->maxLength(255),
                        Forms\Components\Textarea::make('description')
                            ->required()
                            ->columnSpanFull(),
                        Forms\Components\FileUpload::make('attachments')
                            ->multiple()
                            ->downloadable()
                            ->columnSpanFull(),
                        Forms\Components\Select::make('status')
                            ->options([
                                'pending' => 'Pending',
                                'in_progress' => 'In Progress',
                                'resolved' => 'Resolved',
                                'closed' => 'Closed',
                            ])
                            ->default('pending')
                            ->required(),
                    ])->columns(2),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('cun')
                    ->searchable()
                    ->sortable(),
                Tables\Columns\TextColumn::make('type')
                    ->badge()
                    ->color(fn (string $state): string => match ($state) {
                        'peticion' => 'info',
                        'queja' => 'warning',
                        'apelacion' => 'danger',
                        'reposicion' => 'danger',
                    }),
                Tables\Columns\TextColumn::make('first_name')
                    ->label('Client')
                    ->formatStateUsing(fn ($record) => $record->first_name . ' ' . $record->last_name)
                    ->searchable(['first_name', 'last_name']),
                Tables\Columns\TextColumn::make('status')
                    ->label('Estado')
                    ->badge()
                    ->color(fn (string $state): string => match ($state) {
                        'pending' => 'warning',
                        'in_progress' => 'info',
                        'resolved' => 'success',
                        'closed' => 'gray',
                    })
                    ->formatStateUsing(fn (string $state): string => match ($state) {
                        'pending' => 'Pendiente',
                        'in_progress' => 'En Progreso',
                        'resolved' => 'Resuelto',
                        'closed' => 'Cerrado',
                    }),
                Tables\Columns\TextColumn::make('deadline_at')
                    ->label('Fecha Límite')
                    ->date('d/m/Y')
                    ->sortable()
                    ->badge()
                    ->color(fn ($record) => 
                        $record->status === 'resolved' || $record->status === 'closed' ? 'gray' : (
                            $record->deadline_at < now() ? 'danger' : (
                                $record->deadline_at < now()->addDays(3) ? 'warning' : 'success'
                            )
                        )
                    ),
                Tables\Columns\TextColumn::make('created_at')
                    ->label('Radicado')
                    ->dateTime('d/m/Y H:i')
                    ->sortable(),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('status')
                    ->label('Estado')
                    ->options([
                        'pending' => 'Pendiente',
                        'in_progress' => 'En Progreso',
                        'resolved' => 'Resuelto',
                        'closed' => 'Cerrado',
                    ]),
                Tables\Filters\Filter::make('overdue')
                    ->label('Vencidos')
                    ->query(fn (Builder $query): Builder => $query->where('deadline_at', '<', now())->whereNotIn('status', ['resolved', 'closed'])),
                Tables\Filters\SelectFilter::make('type')
                    ->options([
                        'peticion' => 'Petición',
                        'queja' => 'Queja',
                        'apelacion' => 'Recurso de Apelación',
                        'reposicion' => 'Recurso de Reposición',
                    ]),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\Action::make('answer')
                    ->label('Responder')
                    ->icon('heroicon-o-chat-bubble-left-right')
                    ->color('success')
                    ->mountUsing(function (Forms\ComponentContainer $form, Pqrs $record) {
                        if ($record->type === 'peticion' && empty($record->answer)) {
                            $date = now()->locale('es')->translatedFormat('d \d\e F \d\e\l Y');
                            $createdDate = $record->created_at->locale('es')->translatedFormat('d \d\e F \d\e\l Y');
                            
                            $template = "Montería, {$date}\n\n";
                            $template .= "Señor(a):\n";
                            $template .= "{$record->first_name} {$record->last_name}\n";
                            $template .= "Dirección: [Dirección del usuario]\n";
                            $template .= "Número de suscriptor: [Número]\n";
                            $template .= "Correo electrónico: {$record->email}\n";
                            $template .= "Asunto: Respuesta a Derecho de petición presentada por el usuario.\n";
                            $template .= "Referencia: PQR radicada No. {$record->cun}, recibida el día {$createdDate}\n\n";
                            
                            $template .= "1. ANTECEDENTES\n";
                            $template .= "En atención al Derecho de Petición presentado por el(la) señor(a) {$record->first_name} {$record->last_name}, radicado el día {$createdDate}, mediante el cual manifiesta inconformidad con la prestación del servicio técnico y solicita [describir brevemente la solicitud], nos permitimos dar respuesta dentro de los términos legales establecidos.\n";
                            $template .= "2. RESPUESTA\n";
                            $template .= "Después de revisar su caso, los registros técnicos de la red y las órdenes de servicio asociadas, INTALNET TELECOMUNICACIONES informa lo siguiente:\n";
                            $template .= "[Aquí se redacta la respuesta concreta dependiendo del tipo de inconformidad. Ejemplos:]\n";
                            $template .= "El día [fecha], se realizó visita técnica donde se evidenció falla en el servicio de internet y televisión, y se ejecutaron las acciones correctivas necesarias.\n";
                            $template .= "El servicio actualmente se encuentra funcionando correctamente y continuaremos en monitoreo para garantizar su estabilidad.\n";
                            $template .= "Respecto a la facturación, se realizó la revisión detallada del periodo [mes] y se confirmó que usted dejó de disfrutar del servicio durante 5 días. En atención a ello, y conforme a la normatividad vigente sobre la prestación de servicios de telecomunicaciones, procederemos a aplicar el descuento correspondiente en su próxima factura, reflejando el tiempo real en el que el servicio no estuvo disponible para usted.\n";
                            $template .= "(Si corresponde agregar anexos, evidencias técnicas, órdenes de servicio o informes, debe indicarse aquí y adjuntarse).\n\n\n";
                            $template .= "3. FUNDAMENTO LEGAL\n";
                            $template .= "Esta respuesta se emite dando cumplimiento a:\n";
                            $template .= "Artículo 23 de la Constitución Política de Colombia.\n";
                            $template .= "Ley 1755 de 2015 – Derecho fundamental de petición.\n";
                            $template .= "Ley 1341 de 2009 (Ley de TIC) y sus modificaciones.\n";
                            $template .= "Resolución CRC 5111 de 2017 – Régimen de Protección de Usuarios de Servicios de Telecomunicaciones, que establece los lineamientos para la atención y respuesta de PQR por parte de los proveedores de redes y servicios de telecomunicaciones.\n";
                            $template .= "Resolución CRC 3066 de 2011 y demás normas concordantes aplicables al sector.\n\n";
                            $template .= "Resolución CRC 3066 de 2011 y demás normas concordantes aplicables al sector\n";
                            $template .= "En cumplimiento de esta normativa, Intalnet Telecomunicaciones garantiza una atención oportuna, clara y completa a todas las PQR presentadas por sus suscriptores y usuarios.\n";
                            $template .= "4. CIERRE Y CANALES DE CONTACTO\n";
                            $template .= "Agradecemos su comunicación y reiteramos nuestro compromiso con una atención transparente, oportuna y conforme a la normativa vigente.\n";
                            $template .= "Si desea ampliar la información o presentar un nuevo reporte técnico, puede comunicarse al correo: servicioalcliente@intalnet.com, la línea +57 314 8042601, o a través de nuestros canales de soporte técnico.\n";
                            $template .= "Atentamente;\n\n\n\n";
                            $template .= "__________________________________\n";
                            $template .= "ANGELA MARIA SEJIN M.\n";
                            $template .= "Gerente General\n";
                            $template .= "INTALNET TELECOMUNICACIONES \n";
                            $template .= "Correo: servicioalcliente@intalnet.com  \n";
                            $template .= "Teléfono: +57 314 8042601\n\n";
                            $template .= "Anexos (si aplica):\n";
                            $template .= "[Listado de documentos enviados con la respuesta]";

                            $form->fill(['answer' => $template]);
                        } else {
                             $form->fill(['answer' => $record->answer]);
                        }
                    })
                    ->form([
                        Forms\Components\Textarea::make('answer')
                            ->label('Respuesta Oficial')
                            ->required()
                            ->rows(20),
                    ])
                    ->action(function (Pqrs $record, array $data): void {
                        $record->update([
                            'answer' => $data['answer'],
                            'answered_at' => now(),
                            'status' => 'resolved',
                        ]);
                    })
                    ->visible(fn (Pqrs $record) => !in_array($record->status, ['resolved', 'closed'])),
                Tables\Actions\Action::make('downloadResponse')
                    ->label('Descargar Respuesta')
                    ->icon('heroicon-o-document-arrow-down')
                    ->color('primary')
                    ->action(function (Pqrs $record) {
                        return response()->streamDownload(function () use ($record) {
                            echo \Barryvdh\DomPDF\Facade\Pdf::loadView('pdf.pqrs-answer', ['answer' => $record->answer])->output();
                        }, 'respuesta-pqr-' . $record->cun . '.pdf');
                    })
                    ->visible(fn (Pqrs $record) => !empty($record->answer)),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            RelationManagers\MessagesRelationManager::class,
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListPqrs::route('/'),
            'create' => Pages\CreatePqrs::route('/create'),
            'edit' => Pages\EditPqrs::route('/{record}/edit'),
        ];
    }
}
